name: Rflink Build Tests

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio==6.1.5
        pio update
        pip install esptool

    - name: Make a BUILDNAME
      run: echo "RFLINK_BUILDNAME=\"$(date '+%Y%m%d-%H%M%S')-${GITHUB_REF#refs/heads/}\"" >> $GITHUB_ENV

    - name: sonoff_bridge
      run: |
        pio run --project-conf .travis.platformio.ini --environment sonoff_bridge

    - name: Copy firmwares in 1 place
      if: github.event_name == 'push'
      run: |
        mkdir firmwares
        cp .pio/build/sonoff_bridge/firmware.bin firmwares/sonoff_bridge-firmware.bin

    - name: Publish firmware for Master branch
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly dev Build"
        files: |
          firmwares/*
